import argparse
import pickle
import numpy as np
from itertools import combinations
from scipy.optimize import linprog
from typing import Tuple

# =============================================================================
# m-HEIGHT COMPUTATION (included for evaluation of the generated matrix)
# =============================================================================
def compute_z_S_j(G: np.ndarray, S: Tuple[int, ...], j: int) -> float:
    """Solve one LP for a single (S, j) pair."""
    k, n = G.shape
    bar_S = [t for t in range(n) if t not in S]

    c = -G[:, j].astype(np.float64)

    A_ub_list = []
    b_ub_list = []
    for t in bar_S:
        gt = G[:, t].astype(np.float64)
        A_ub_list.append(gt)
        b_ub_list.append(1.0)
        A_ub_list.append(-gt)
        b_ub_list.append(1.0)

    res = linprog(
        c=c,
        A_ub=np.array(A_ub_list),
        b_ub=np.array(b_ub_list),
        bounds=[(-1e6, 1e6)] * k,
        method='highs',
        options={'presolve': True, 'disp': False}
    )

    if res.success:
        return float(-res.fun)
    elif "unbounded" in (res.message or "").lower():
        return float('inf')
    else:
        return 1.0


def m_height(G: np.ndarray, m: int) -> float:
    """Exact m-height of the code generated by G."""
    k, n = G.shape
    if m == 0:
        return 1.0

    max_h = 1.0
    for S in combinations(range(n), m):
        S = tuple(S)
        for j in S:
            z = compute_z_S_j(G, S, j)
            if z > max_h:
                max_h = z
    return max_h


# =============================================================================
# ANGLE-BASED COST (the exact criterion you described)
# =============================================================================
def angle_based_cost(G: np.ndarray, m: int) -> float:
    """
    For each column i (initial vector):
        - Find the m-1 other columns closest in angle to it.
        - Form the subset of m columns.
        - Find the largest angle in that subset (most orthogonal pair).
    Return the WORST (maximum) such angle over all starting columns.
    The optimizer tries to MINIMIZE this value.
    """
    n = G.shape[1]
    # Column norms (add epsilon to avoid division by zero)
    norms = np.linalg.norm(G, axis=0) + 1e-12
    # Absolute cosine similarity (angles are unsigned, directions can be flipped)
    cos_matrix = np.abs(G.T @ G) / np.outer(norms, norms)
    ang_matrix = np.arccos(np.clip(cos_matrix, -1.0, 1.0))

    worst_angle = 0.0

    for i in range(n):
        # Angles from column i to all others
        other_mask = np.arange(n) != i
        ang_to_others = ang_matrix[i, other_mask]

        # Indices of the m-1 closest columns
        closest_rel = np.argsort(ang_to_others)[:m-1]
        other_indices = np.where(other_mask)[0]
        subset_idx = [i] + list(other_indices[closest_rel])

        # All pairwise angles inside the subset
        sub_angles = ang_matrix[np.ix_(subset_idx, subset_idx)]

        # Largest angle in this subset = angle between the most orthogonal pair
        max_in_subset = np.max(sub_angles)

        if max_in_subset > worst_angle:
            worst_angle = max_in_subset

    return worst_angle


# =============================================================================
# LOCAL IMPROVEMENT (greedy ±1 on P using the angle cost)
# =============================================================================
def local_improve_angle(P: np.ndarray, m: int) -> np.ndarray:
    """
    Greedy local search that minimizes the angle-based cost.
    Runs until no single ±1 change improves the cost.
    """
    P = P.copy().astype(int)
    k, p_dim = P.shape
    n = k + p_dim

    # Current best
    G = np.hstack([np.eye(k), P.astype(float)])
    current_cost = angle_based_cost(G, m)

    improved = True
    while improved:
        improved = False
        for i in range(k):
            for j in range(p_dim):
                for delta in [-1, 1]:
                    P_new = P.copy()
                    P_new[i, j] += delta

                    # Skip if it creates a zero column
                    if np.all(P_new[:, j] == 0):
                        continue

                    G_new = np.hstack([np.eye(k), P_new.astype(float)])
                    new_cost = angle_based_cost(G_new, m)

                    if new_cost < current_cost:
                        P = P_new
                        current_cost = new_cost
                        improved = True
                        print(f"    Angle-improve: P[{i},{j}] += {delta} → cost = {current_cost:.4f}")
                        break
                if improved:
                    break
            if improved:
                break

    return P


# =============================================================================
# MAIN SCRIPT
# =============================================================================
def main():
    parser = argparse.ArgumentParser(
        description="Generate systematic generator matrix [I_k | P] that minimizes "
                    "the angle between the most orthogonal vectors in every "
                    "local m-subset (defined by closest-angle neighbors)."
    )
    parser.add_argument('--k', type=int, required=True, help='Number of rows (dimension)')
    parser.add_argument('--n', type=int, required=True, help='Number of columns')
    parser.add_argument('--m', type=int, required=True, help='m parameter')
    parser.add_argument('--trials', type=int, default=2000,
                        help='Number of random P matrices to try (default: 2000)')
    parser.add_argument('--low', type=int, default=-10, help='Lower bound for P entries')
    parser.add_argument('--high', type=int, default=10, help='Upper bound for P entries')
    parser.add_argument('--output', default=None,
                        help='If given, save the best P as a pickle "generatorMatrix" dict')
    parser.add_argument('--no-local', action='store_true',
                        help='Skip the local ±1 improvement step')

    args = parser.parse_args()

    if args.k >= args.n or args.m < 1 or args.m > args.n:
        parser.error("Invalid dimensions: require k < n and 1 ≤ m ≤ n")

    p_dim = args.n - args.k

    best_cost = float('inf')
    best_P = None
    best_h = None
    best_G = None

    print(f"Searching for best P ({args.k}×{p_dim}) using angle-based criterion...\n")

    for trial in range(args.trials):
        # Random integer P with no all-zero columns
        while True:
            P = np.random.randint(args.low, args.high + 1, size=(args.k, p_dim))
            if np.all(np.any(P != 0, axis=0)):
                break

        G = np.hstack([np.eye(args.k), P.astype(float)])
        cost = angle_based_cost(G, args.m)

        if cost < best_cost:
            best_cost = cost
            best_P = P.copy()
            best_G = G.copy()

            # Also compute true m-height for evaluation
            try:
                h = m_height(G, args.m)
                best_h = h
            except Exception:
                h = None

            print(f"Trial {trial+1:4d}/{args.trials} | angle-cost = {cost:.4f} rad "
                  f"| m-height = {h:.6f if h is not None else 'N/A'}")

    # Final local improvement (greedy ±1 on the angle cost)
    if not args.no_local and best_P is not None:
        print("\nRunning local ±1 improvement on angle cost...")
        best_P = local_improve_angle(best_P, args.m)
        best_G = np.hstack([np.eye(args.k), best_P.astype(float)])
        best_cost = angle_based_cost(best_G, args.m)
        best_h = m_height(best_G, args.m)

    # Results
    print("\n" + "="*60)
    print("FINAL RESULT")
    print("="*60)
    print("P matrix (k × (n-k)):")
    print(best_P)
    print(f"\nAngle-based cost (minimized): {best_cost:.4f} radians")
    if best_h is not None:
        print(f"True m-height of the code: {best_h:.6f}")
    print(f"Generator matrix shape: {best_G.shape}")

    # Optional pickle output (exactly the format required by the project)
    if args.output and best_P is not None:
        out_dict = {(args.n, args.k, args.m): best_P}
        with open(args.output, "wb") as f:
            pickle.dump(out_dict, f)
        print(f"\nSaved generatorMatrix dict to: {args.output}")


if __name__ == "__main__":
    main()