import pickle
import os
import numpy as np
from itertools import combinations
from scipy.optimize import linprog
from typing import List, Tuple


def compute_z_S_j(G: np.ndarray, S: Tuple[int, ...], j: int) -> float:
    """
    Solve one LP: maximize G[:, j] @ u
    s.t. -1 <= G[:, t] @ u <= 1  for all t in bar{S}
    """
    k, n = G.shape
    bar_S = [t for t in range(n) if t not in S]

    # Objective: maximize G[:,j] @ u  → linprog minimizes -c
    c = -G[:, j].astype(np.float64)

    # Build inequality constraints A_ub @ u <= b_ub
    A_ub_list: List[np.ndarray] = []
    b_ub_list: List[float] = []
    for t in bar_S:
        gt = G[:, t].astype(np.float64)
        A_ub_list.append(gt)      # gt @ u <= 1
        b_ub_list.append(1.0)
        A_ub_list.append(-gt)     # -gt @ u <= 1
        b_ub_list.append(1.0)

    res = linprog(
        c=c,
        A_ub=np.array(A_ub_list),
        b_ub=np.array(b_ub_list),
        bounds=None,
        method='highs',                    # fastest available solver
        options={'presolve': True, 'disp': False}
    )

    if res.success:
        return float(-res.fun)
    elif res.message and "unbounded" in res.message.lower():
        return float('inf')
    else:
        raise RuntimeError(f"LP failed for S={S}, j={j}: {res.message}")


def m_height(G: np.ndarray, m: int) -> float:
    """
    Compute the m-height h_m(C) of the analog code generated by G
    (exactly as defined in the project document).

    This version is optimized for a **single process** (no multiprocessing).
    It is the fastest possible serial implementation.
    """
    k, n = G.shape
    if not (0 <= m < n):
        raise ValueError(f"m must be in [0, {n-1}], got {m}")

    if m == 0:
        return 1.0

    # All m-subsets of {0, 1, ..., n-1}
    subsets = combinations(range(n), m)

    max_h = 1.0
    for S in subsets:
        S = tuple(S)                     # combinations yields tuples already
        for j in S:
            z = compute_z_S_j(G, S, j)
            if z > max_h:
                max_h = z

    return max_h


def print_generator_matrices():
    """
    Reads the saved 'generatorMatrix' and 'mHeight' pickle files
    and prints EVERY stored generator matrix in a clean, visually pleasing format.
    
    - Loads both files automatically.
    - For each (n, k, m):
        • Shows the m-height
        • Prints the parity matrix P (integers, nicely aligned)
        • Prints the full systematic generator matrix G = [I_k | P] (floats)
    - Sorted by (n, k, m) for easy reading.
    - Uses fixed-width formatting, clear borders, and rounded values.
    """
    if not os.path.exists("generatorMatrixTempCp"):
        print("❌ No 'generatorMatrix' file found in the current directory.")
        print("   Run the main hill-climbing search first to generate matrices.")
        return

    # Load the saved results
    with open("generatorMatrixTempCp", "rb") as f:
        generatorMatrix = pickle.load(f)
    with open("mHeightTempCp", "rb") as f:
        mHeight = pickle.load(f)

    if not generatorMatrix:
        print("⚠️  generatorMatrix file is empty.")
        return

    print("🚀 LOADED GENERATOR MATRICES")
    print("=" * 90)

    # Sort keys for consistent output order
    for key in sorted(generatorMatrix.keys()):
        n, k, m = key
        P = generatorMatrix[key]          # k × (n-k) integer matrix
        r = n - k
        I = np.eye(k)
        G = np.hstack((I, P.astype(float)))
        h = m_height(G, m)

        # Build full systematic G = [I_k | P]

        # ====================== VISUALLY PLEASING PRINT ======================
        print(f"\n📌  (n={n}, k={k}, m={m})")
        print(f"   m-height h_m(C) = {h:.10f}")
        print(f"   P  (parity matrix, {k}×{r})")
        
        # Pretty P (integers, right-aligned, fixed width)
        print("   " + "─" * (r * 8))
        for row in P:
            print("   " + " ".join(f"{int(x):6d}" for x in row))
        print("   " + "─" * (r * 8))

        # Full G (floats, 6 decimal places, clean)
        print(f"   Full systematic G = [I_k | P]   ({k}×{n})")
        np.set_printoptions(precision=0, suppress=True, linewidth=120, floatmode='fixed')
        print(G)
        np.set_printoptions()   # reset global settings

        print("-" * 90)

    print(f"\n✅ Printed {len(generatorMatrix)} generator matrices successfully!")
    print("   (Files: generatorMatrix + mHeight)")


# ====================== EXAMPLE USAGE ======================
if __name__ == "__main__":
    # Just call this function whenever you want a beautiful overview
    print_generator_matrices()

    # Optional: you can also call it after the hill-climbing search
    # (just put print_generator_matrices() at the very end of your main script)