import numpy as np
from itertools import combinations
from scipy.optimize import linprog
from typing import List, Tuple


def compute_z_S_j(G: np.ndarray, S: Tuple[int, ...], j: int) -> float:
    """
    Solve one LP: maximize G[:, j] @ u
    s.t. -1 <= G[:, t] @ u <= 1  for all t in bar{S}
    """
    k, n = G.shape
    bar_S = [t for t in range(n) if t not in S]

    # Objective: maximize G[:,j] @ u  → linprog minimizes -c
    c = -G[:, j].astype(np.float64)

    # Build inequality constraints A_ub @ u <= b_ub
    A_ub_list: List[np.ndarray] = []
    b_ub_list: List[float] = []
    for t in bar_S:
        gt = G[:, t].astype(np.float64)
        A_ub_list.append(gt)      # gt @ u <= 1
        b_ub_list.append(1.0)
        A_ub_list.append(-gt)     # -gt @ u <= 1
        b_ub_list.append(1.0)

    res = linprog(
        c=c,
        A_ub=np.array(A_ub_list),
        b_ub=np.array(b_ub_list),
        bounds=None,
        method='highs',                    # fastest available solver
        options={'presolve': True, 'disp': False}
    )

    if res.success:
        return float(-res.fun)
    elif res.message and "unbounded" in res.message.lower():
        return float('inf')
    else:
        raise RuntimeError(f"LP failed for S={S}, j={j}: {res.message}")


def m_height(G: np.ndarray, m: int) -> float:
    """
    Compute the m-height h_m(C) of the analog code generated by G
    (exactly as defined in the project document).

    This version is optimized for a **single process** (no multiprocessing).
    It is the fastest possible serial implementation.
    """
    k, n = G.shape
    if not (0 <= m < n):
        raise ValueError(f"m must be in [0, {n-1}], got {m}")

    if m == 0:
        return 1.0

    # All m-subsets of {0, 1, ..., n-1}
    subsets = combinations(range(n), m)

    max_h = 1.0
    for S in subsets:
        S = tuple(S)                     # combinations yields tuples already
        for j in S:
            z = compute_z_S_j(G, S, j)
            if z > max_h:
                max_h = z

    return max_h


# =============================================================================
# Example / test (matches the document's Example 6 exactly)
# =============================================================================
if __name__ == "__main__":
    # Generator matrix from the project document (k=2, n=5)
    P = np.array([
        [ 0,  0, -1,  0,  1],
        [ 0,  0,  2,  0, -2],
        [ 0,  1,  0,  1,  0],
        [ 2,  0,  0,  2,  0]
    ], dtype=float)

    P = np.hstack((np.eye(4), P.astype(float)))

    # G_example = np.array(
    #     [
    #         [1.0, 0.0, 0.4759809, 0.9938236, 0.819425],
    #         [0.0, 1.0, -0.8960798, -0.7442706, 0.3345122],
    #     ],
    #     dtype=float,
    # )

    # Compute h_2(C) - should be approximately 1.9242387
    # h2 = m_height(P, m=2, parallel=True)
    # print(f"Computed h_2(C) = {h2:.10f}  (matches document value)")

    # You can easily extend this to compute the full height profile:
    for m in range(9):
        print(f"h_{m+1}(C) = {m_height(P, m)}")