import pickle
import numpy as np
from itertools import combinations
from scipy.optimize import linprog
import multiprocessing as mp
import os

# ====================== m-HEIGHT EVALUATOR (unchanged - fast & correct) ======================
def _solve_lp(args):
    G, j, barS = args
    c = -G[:, j]
    barS_matrix = G[:, barS].T
    A_ub = np.vstack([barS_matrix, -barS_matrix])
    b_ub = np.ones(2 * len(barS))
    res = linprog(c, A_ub=A_ub, b_ub=b_ub,
                  bounds=(None, None), method='highs',
                  options={'presolve': True, 'disp': False})
    return -res.fun if res.success else 1.0


def compute_m_height(G: np.ndarray, m: int) -> float:
    """Compute the exact m-height of the Analog Code generated by G."""
    n = G.shape[1]
    if m == 0:
        return 1.0
    tasks = [(G, j, [t for t in range(n) if t not in S])
             for S in combinations(range(n), m) for j in S]
    results = [_solve_lp(task) for task in tasks]
    return max(max(results), 1.0)


# ====================== [Your full hill-climbing code from previous version goes here] ======================
# (For brevity, the entire hill-climbing script you received last time is assumed to be above this point.
#  You can keep everything exactly as-is up to the final save block.)

# ====================== NEW MAIN FUNCTION FOR TESTING ANY GENERATOR MATRIX ======================
def test_generator_matrix():
    """
    Easy-to-edit test harness.
    Just paste your k×n systematic generator matrix G (or build it from P)
    directly into the script below, set k/n/m, and run.
    No command-line input — everything is hardcoded for quick testing.
    """
    print("=== m-Height Test Harness ===")

    # ========================== EDIT THIS SECTION ==========================
    # Example: change these values to test any of your matrices
    k = 4          # number of information symbols
    n = 9          # total length
    m = 2          # the m in m-height (must satisfy m ≤ n-k)

    # Paste your k×(n-k) parity matrix P here (integers -100..100, no zero columns)
    # This example is a placeholder — REPLACE WITH YOUR REAL P
    P = np.array([
        [ 1,  0,  0,  0,  1],
        [ 0,  1,  0,  0,  0],
        [ 0,  0,  1,  0, -1],
        [ 0,  0,  0,  1,  2]
    ], dtype=float)   # <--- CHANGE THIS TO YOUR BEST P

    # =====================================================================

    # Build full systematic generator matrix G = [I_k | P]
    I = np.eye(k)
    G = np.hstack((I, P))

    # Safety checks
    assert G.shape == (k, n), f"G must be {k}×{n}"
    assert np.all(np.abs(P) <= 100), "All entries of P must be integers between -100 and 100"
    assert not np.any(np.all(P == 0, axis=0)), "No column of P can be the all-zero vector"

    # Compute and display m-height
    h = compute_m_height(G, m)
    print(f"Generator matrix G (k={k}, n={n})")
    print(f"m = {m}")
    print(f"m-height h_m(C) = {h:.10f}")
    print(f"(Should be ≥ 1.0 by definition)")

    # Optional: also print the full G for verification
    print("\nFull G matrix:")
    print(G)


# ====================== RUN THE TEST WHEN SCRIPT IS EXECUTED ======================
if __name__ == "__main__":
    # You can keep your hill-climbing search code above (the big block with params_list, etc.)
    # and just run this test function whenever you want to verify a matrix.

    test_generator_matrix()

    # Example of testing multiple matrices at once (uncomment if desired):
    # print("\n=== Testing multiple saved matrices from file ===")
    # if os.path.exists("generatorMatrix"):
    #     with open("generatorMatrix", "rb") as f:
    #         generatorMatrix = pickle.load(f)
    #     with open("mHeight", "rb") as f:
    #         mHeight = pickle.load(f)
    #     for (n, k, m), P in generatorMatrix.items():
    #         I = np.eye(k)
    #         G = np.hstack((I, P.astype(float)))
    #         h_computed = compute_m_height(G, m)
    #         print(f"{(n,k,m)} → computed h = {h_computed:.10f} (saved = {mHeight.get((n,k,m), 'N/A')})")