import numpy as np
from itertools import combinations
from scipy.optimize import linprog
import multiprocessing as mp
from typing import List, Tuple


def compute_z_S_j(G: np.ndarray, S: Tuple[int, ...], j: int) -> float:
    """
    Solve the LP for z_{S,j}: maximize G[:, j] @ u
    subject to -1 <= G[:, t] @ u <= 1 for all t in bar{S}.
    
    Returns the optimal objective value (or inf if unbounded).
    """
    k, n = G.shape
    bar_S = [t for t in range(n) if t not in S]

    # Objective: maximize G[:, j] @ u  =>  linprog minimizes -obj
    c = -G[:, j].astype(float)

    # Inequality constraints: A_ub @ u <= b_ub
    A_ub_list: List[np.ndarray] = []
    b_ub_list: List[float] = []
    for t in bar_S:
        gt = G[:, t].astype(float)
        # gt @ u <= 1
        A_ub_list.append(gt)
        b_ub_list.append(1.0)
        # -gt @ u <= 1  <=>  gt @ u >= -1
        A_ub_list.append(-gt)
        b_ub_list.append(1.0)

    A_ub = np.array(A_ub_list)
    b_ub = np.array(b_ub_list)

    # No variable bounds (u unbounded)
    res = linprog(
        c,
        A_ub=A_ub,
        b_ub=b_ub,
        bounds=None,
        method="highs",          # fastest for small LPs
        options={"presolve": True, "disp": False}
    )

    if res.success:
        return float(-res.fun)   # optimal value of original maximization
    elif res.message and "unbounded" in res.message.lower():
        return float("inf")
    else:
        # Should never happen for feasible LPs (u=0 is always feasible)
        raise RuntimeError(
            f"LP solver failed for S={S}, j={j}: {res.message}\n"
            f"res.status={res.status}"
        )


def _process_subset(args: Tuple[np.ndarray, Tuple[int, ...]]) -> float:
    """
    Top-level (picklable) worker for multiprocessing.
    Computes max_{j in S} z_{S,j} for one subset S.
    """
    G, S = args
    local_max = 0.0
    for j in S:
        z = compute_z_S_j(G, S, j)
        if z > local_max:
            local_max = z
    return local_max


def m_height(G: np.ndarray, m: int, parallel: bool = True) -> float:
    """
    Compute the m-height h_m(C) of the analog code generated by the
    full-rank k x n generator matrix G (as defined in the project document).

    This version is fully parallelized (all independent LPs run in parallel
    across CPU cores) and uses only top-level picklable functions so that
    multiprocessing works reliably when the function is imported.

    Parameters
    ----------
    G : np.ndarray
        Shape (k, n). Generator matrix (real-valued, full rank, no zero columns).
    m : int
        The height index (0 <= m <= n-k).
    parallel : bool
        Whether to use multiprocessing (highly recommended; uses all CPU cores).

    Returns
    -------
    float
        The m-height h_m(C) = max_{S in Lambda(n,m), j in S} z_{S,j}.
        Always >= 1.0 (per the project definition).
    """
    k, n = G.shape
    if not (0 <= m < n):
        raise ValueError(f"m must be in [0, n-1], got {m}")
    if m == 0:
        return 1.0

    # All subsets S subset of [0..n-1] with |S| = m
    subsets: List[Tuple[int, ...]] = list(combinations(range(n), m))

    if parallel and len(subsets) > 1:
        # Prepare arguments for the top-level worker
        tasks = [(G, S) for S in subsets]
        with mp.Pool(processes=mp.cpu_count()) as pool:
            subset_maxes = pool.map(_process_subset, tasks)
        h = max(subset_maxes)
    else:
        # Fallback to serial (still very fast for n=9)
        h = max(_process_subset((G, S)) for S in subsets)

    # Per the project definition, h_m(C) >= 1
    return max(h, 1.0)


# =============================================================================
# Example / test (matches the document's Example 6 exactly)
# =============================================================================
if __name__ == "__main__":
    # Generator matrix from the project document (k=2, n=5)
    P = np.array([
        [ 0,  0, -1,  0,  1],
        [ 0,  0,  2,  0, -2],
        [ 0,  1,  0,  1,  0],
        [ 2,  0,  0,  2,  0]
    ], dtype=float)

    P = np.hstack((np.eye(4), P.astype(float)))

    # G_example = np.array(
    #     [
    #         [1.0, 0.0, 0.4759809, 0.9938236, 0.819425],
    #         [0.0, 1.0, -0.8960798, -0.7442706, 0.3345122],
    #     ],
    #     dtype=float,
    # )

    # Compute h_2(C) - should be approximately 1.9242387
    # h2 = m_height(P, m=2, parallel=True)
    # print(f"Computed h_2(C) = {h2:.10f}  (matches document value)")

    # You can easily extend this to compute the full height profile:
    for m in range(9):
        print(f"h_{m+1}(C) = {m_height(P, m)}")